// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnHub.Models;

public partial class Chats
{
    public int ChatId { get; set; }

    public int FirstParticipant { get; set; }

    public int SecondParticipant { get; set; }

    public virtual Users FirstParticipantNavigation { get; set; }

    public virtual ICollection<Messages> Messages { get; set; } = new List<Messages>();

    public virtual Users SecondParticipantNavigation { get; set; }
}