// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnHub.Models;

public partial class Lessons
{
    public int LessonId { get; set; }

    public string Title { get; set; }

    public DateTime PublicationDate { get; set; }

    public int CourseId { get; set; }

    public virtual ICollection<Assignments> Assignments { get; set; } = new List<Assignments>();

    public virtual Courses Course { get; set; }

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();
}