// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnHub.Models;

public partial class Messages
{
    public int MessageId { get; set; }

    public string MessageText { get; set; }

    public DateTime SentDate { get; set; }

    public int SenderId { get; set; }

    public int RecipientId { get; set; }

    public int ChatId { get; set; }

    public virtual Chats Chat { get; set; }

    public virtual Users Recipient { get; set; }

    public virtual Users Sender { get; set; }
}