// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnHub.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Mail { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public DateTime RegistrationDate { get; set; }

    public virtual ICollection<Chats> ChatsFirstParticipantNavigation { get; set; } = new List<Chats>();

    public virtual ICollection<Chats> ChatsSecondParticipantNavigation { get; set; } = new List<Chats>();

    public virtual ICollection<Enrollments> Enrollments { get; set; } = new List<Enrollments>();

    public virtual ICollection<Grades> Grades { get; set; } = new List<Grades>();

    public virtual ICollection<Messages> MessagesRecipient { get; set; } = new List<Messages>();

    public virtual ICollection<Messages> MessagesSender { get; set; } = new List<Messages>();

    public virtual ICollection<Progress> Progress { get; set; } = new List<Progress>();

    public virtual ICollection<UserCourse> UserCourse { get; set; } = new List<UserCourse>();
}